name: frontend-prod-deploy

on:
  push:
    branches: ["main"]
    paths:
      - "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.EC2_DEPLOY_DIR }}
            source ~/.bashrc
            source ~/.nvm/nvm.sh
            nvm use 22.16.0
            git pull origin main
            yarn install --frozen-lockfile
            yarn build
            pm2 restart ecosystem.config.js --update-env
