name: frontend-prod-deploy

on:
  push:
    branches: ["main"]
    paths:
      - "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          DEPLOY_DIR: ${{ secrets.EC2_DEPLOY_DIR }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "$DEPLOY_DIR"
            git pull origin main
            yarn install
            yarn build
            pm2 restart ecosystem.config.js
